on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -f ./Dockerfile.dev -t akosfi/imager-frontend:latest .
      - name: Lint
        run: docker run akosfi/imager-frontend npm run lint
      - name: Test
        run: docker run akosfi/imager-frontend npm run test