on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: docker build -t akosfi/imager-frontend:latest .